language: csharp
solution: Markdown/Markdown.sln
before_install:
    - chmod +x scripts/run_benchmark.sh
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore Markdown/Markdown.sln
script:
    - xbuild /p:Configuration=Release Markdown/Markdown.sln
    - scripts/run_benchmark.sh
branches:
    except:
    - benchmarks